version: "3.9"

services:
  entry_point:
    container_name: entry_point_container
    build: ./entry_point/
    environment:
      - USER_INFORMATION_SERVICE_URL=http://user_information_container:3206
      - PLAYER_SERVICE_URL=http://player_container:3201
      - MATCH_SERVICE_URL=http://match_container:3204
      - STAT_SERVICE_URL=http://stat_container:3205
      - STORE_SERVICE_URL=http://store_container:3203
      - NOMEKOP_SERVICE_URL=http://nomekop_container:3202
    ports:
      - "3200:3200"
  player:
    container_name: player_container
    build: ./player/
    environment:
      - NOMEKOP_SERVICE_URL=http://nomekop_container:3202
      - STORE_SERVICE_URL=http://store_container:3203
      - MATCH_SERVICE_URL=http://match_container:3204

  nomekop:
    container_name: nomekop_container
    build: ./nomekop/

  store:
    container_name: store_container
    build: ./store/
    environment:
      - NOMEKOP_SERVICE_URL=http://nomekop_container:3202

  match:
    container_name: match_container
    build: ./match/
    environment:
      - STAT_SERVICE_URL=http://stat_container:3205
      - NOMEKOP_SERVICE_URL=http://nomekop_container:3202

  stat:
    container_name: stat_container
    build: ./stat/

  user_information:
    container_name: user_information_container
    build: ./user_information/
    environment:
      - PLAYER_SERVICE_URL=http://player_container:3201
